# Site settings
title: Linda Alley
email: lindaalleywriter@gmail.com
description: > #Linda Alley is a writer of fiction, travel articles and teaching resources. She is based in Melbourne, Australia.#
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lindaalley.com" # the base hostname & protocol for your site
twitter_username: lindaalleywrite
facebook_username: LindaAlleyWriter

# Build settings
markdown: kramdown
permalink: pretty

prose:
  siteurl: 'http://lindaalley.github.io/'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
          alterable: true
